### ISSUE TITLE
Can the client script use a feed directly from the webcam or attached camera?

### ISSUE THREAD

**Issue by didlie** [pldubouilh/live-torrent#8]
1) is it possible to stream directly from a webcam, allowing for a p2p torrent broadcast? -- whats the code?
2) can you compile the code with dependencies into a single client side js script?
3) I haven't read the code yet... so maybe you can tell me the possibility of easily creating the magnet links server-side using php instead of a node server.

**Comment by pldubouilh** [comment]
1/ Probably possible, no clue of how the code would look like, and this library is probably not the right place to start
2/ Only HLS.JS is a deps at the moment, including it to the bundle just takes to add a `require('hls.js')` line on top of the `loader.js` and re-run browserify
3/ No clue of php instead of node. Most of the libraries used (`create-torrent`, etc...) are node only though
